#!/bin/bash
# make-index.sh — summarises what was captured into INDEX.md, next to the images.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

cd "$OUT_ROOT"

{
    echo "# Awful Screenshot Matrix"
    echo
    echo "Generated by \`Scripts/screenshot-matrix/make-index.sh\`. Every PNG carries a"
    echo "burned-in label strip along the bottom naming the iOS version, device, theme"
    echo "and view. See \`Scripts/screenshot-matrix/README.md\` for how to regenerate."
    echo
    echo "Total images: $(find . -name '*.png' | wc -l | tr -d ' ')"
    echo
    echo "## Per device"
    echo
    echo "| Device folder | Themes | Images |"
    echo "|---|---|---|"
    for dir in ios*/; do
        [ -d "$dir" ] || continue
        themes=$(find "$dir" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')
        imgs=$(find "$dir" -name '*.png' | wc -l | tr -d ' ')
        echo "| ${dir%/} | $themes | $imgs |"
    done
    echo
    echo "## Per theme (all devices)"
    echo
    echo "| Theme | Images |"
    echo "|---|---|"
    find . -mindepth 2 -maxdepth 2 -type d | sed 's|.*/||' | sort -u \
        | while read -r theme; do
            n=$(find . -path "*/$theme/*.png" | wc -l | tr -d ' ')
            echo "| $theme | $n |"
        done
    echo
    echo "## Views captured"
    echo
    find . -name '*.png' | sed -E 's/.*_([0-9]+-[a-z-]+)\.png/\1/' | sort -u | sed 's/^/- /'
} > INDEX.md

echo "wrote $OUT_ROOT/INDEX.md"
