require 'open3'

FILES = "- awful.js"

task :default => [ :assemble ]

desc "assemble posts-view.js"
task :assemble do
  Open3.popen3("cat #{FILES} > posts-view.js") do |i, _, _|
    # Shorten long tap interval.
    i.print File.read("../../Vendor/zepto/zepto.min.js").gsub("750", "500")
    i.close
  end
end
