//  AppIconImageNames.swift
//
//  Copyright 2025 Awful Contributors. CC BY-NC-SA 3.0 US https://github.com/Awful/Awful.app

/**
 App icon image names generated from the contents of `App Icons.xcassets`.

 Generated by `Scripts/app-icons`. Change that, don't change this!
 */
enum AppIconImageNames {
    static let cute: String = "cute_appicon"
    static let five: String = "five_appicon"
    static let froggo: String = "froggo_appicon"
    static let froggo_purple: String = "froggo_purple_appicon"
    static let ghost_blue: String = "ghost_blue_appicon"
    static let greenface: String = "greenface_appicon"
    static let rated_five: String = "rated_five_appicon"
    static let rated_five_pride: String = "rated_five_pride_appicon"
    static let rated_five_trans: String = "rated_five_trans_appicon"
    static let riker: String = "riker_appicon"
    static let smith: String = "smith_appicon"
    static let stare: String = "stare_appicon"
    static let staredog: String = "staredog_appicon"
    static let staredog_tongue: String = "staredog_tongue_appicon"
    static let v: String = "v_appicon"
}
