#!/usr/bin/env bash
set -e

SIZES=(1536x2008               2048x1496                640x1136            640x960)
NAMES=(Default-Portrait@2x.png Default-Landscape@2x.png Default-568h@2x.png Default@2x.png)

SCRIPTDIR="$(cd "$(dirname "$0")"; pwd)"
"$SCRIPTDIR"/tagcollage "${SIZES[@]}"

for i in "${!SIZES[@]}"; do
  mv "$SCRIPTDIR"/collage-"${SIZES[$i]}".png "$SCRIPTDIR"/${NAMES[$i]}
done
