#!/usr/bin/env bash
set -e

IGNORE=(
  ama
  icon-37-selling
  icon-38-buying
  icon-46-trading
  icon-52-trading
  tma
)

if [ $# -eq 0 ]; then
  cat <<-USAGE
Usage: `basename "$0"` size [size...]

size - The width and height of the collage.

Output: collage-size.png for each size argument.
USAGE
  exit 1
fi

command -v gm >/dev/null 2>&1 || {
  echo >&2 "Please install graphicsmagick! brew install graphicsmagick"
  exit 1
}

IGNORE=$(IFS="|"; echo "${IGNORE[*]}")

SCRIPTDIR="$(cd "$(dirname "$0")"; pwd)"
TAGDIR="${SCRIPTDIR}/../Resources/Thread Tags"
IFS="$(printf '\n\t')"
IMAGES=($(find -E "$TAGDIR" -name "*.png" \! -regex ".*("$IGNORE").png$"))

# http://stackoverflow.com/a/5533586
size=${#IMAGES[*]}
max=$(( 32768 / size * size ))
for (( i=size-1; i>0; i-- )); do
  while (( (rand=$RANDOM) >= max )); do :; done
  rand=$(( rand % (i+1) ))
  tmp="${IMAGES[i]}" IMAGES[i]="${IMAGES[rand]}" IMAGES[rand]="$tmp"
done

TILESIZE=$(gm identify "${IMAGES[0]}" | cut -d " " -f 4 | cut -d "+" -f 1)
IFS="x" read -a TILESIZE <<< "$TILESIZE"

divroundup() {
  echo $(( ($1 + ($2 - 1)) / $2))
}

for size in "$@"; do
  IFS="x" read -a sizes <<< "$size"
  tiles=$(divroundup ${sizes[0]} ${TILESIZE[0]})x$(divroundup ${sizes[1]} ${TILESIZE[1]}) 
  outfile="collage-${size}.png"
  gm montage -geometry "$TILESIZE+0+0" -tile "$tiles" -colorspace GRAY "${IMAGES[@]}" "$outfile"
  gm mogrify -fill "#5552" -draw "rectangle 0,0 99999,99999" -crop "${sizes[0]}x${sizes[1]}+0+0" "$outfile"
done
