#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import bump

parser = argparse.ArgumentParser(description="Bump the (short) bundle version, then tag and commit the change")
group = parser.add_mutually_exclusive_group(required=True)
group.add_argument('--build', dest='bump', action='store_const', const=bump.build,
                   help="Bump the build number (e.g. 31501 -> 31502, 3.15 -> 3.15)")
group.add_argument('--minor', dest='bump', action='store_const', const=bump.minor,
                   help="Bump the minor number (e.g. 31501 -> 31600, 3.15 -> 3.16)")
group.add_argument('--major', dest='bump', action='store_const', const=bump.major,
                   help="Bump the major number (e.g. 31501 -> 40000, 3.15 -> 4.0)")
args = parser.parse_args()
bump.bump_version(args.bump)
