name: CI

on:
  push:
    branches:
      - ci
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: xcodebuild test
      run: xcodebuild -project Awful.xcodeproj -scheme Awful -configuration Debug -destination "platform=iOS Simulator,name=iPhone 16,OS=18.0" test
