name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: xcodebuild test
      run: >
        xcodebuild
          -workspace Awful.xcworkspace
          -scheme Awful
          -configuration Debug
          -destination "platform=iOS Simulator,name=iPhone 11,OS=latest"
          test
