name: CI

on:
  push:
    branches:
      - ci
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: xcodebuild test
      run: xcodebuild -project Awful.xcodeproj -scheme Awful -configuration Debug -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" test
